# Generated by Django 3.0.6 on 2021-01-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210116_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product Details not Available'),
        ),
    ]
