# Generated by Django 3.0.6 on 2021-01-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210116_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(default='Specification not Available'),
        ),
    ]
